language: python
python:
  - "2.7"
  - "3.2"
# command to install dependencies
install: "pip install -r requirements.txt"
services:
  - mongodb
# command to run tests
script: 
  - nosetests --with-coverage --cover-package=recordkeeper tests/*

